### ISSUE TITLE
Support datetime and date type.

### ISSUE THREAD

**Issue by yassun7010** [elda27/pydantic_argify#8]
`pydantic` has `datetime` and `date` validation functions, and argparse also has validation methods using `fromisoformat`.

By using these features, datetime support is added.

**Comment by elda27** [comment]
I seem the type annotation should cover most widely cases written in pydantic document, and `str` is the best.

https://docs.pydantic.dev/2.0/usage/types/datetime/

By the way, you may mistake how to write the PR number in your pull request #7.
You need to write #8 in your pull request actually.

**Comment by yassun7010** [comment]
> By the way, you may mistake how to write the PR number in your pull request https://github.com/elda27/pydantic_argify/pull/7.
You need to write https://github.com/elda27/pydantic_argify/issues/8 in your pull request actually.

Thanks. I fixed.

**Comment by yassun7010** [comment]
> I seem the type annotation should cover most widely cases written in pydantic document, and str is the best.

Is this correct in that you intend to add support for `time` and `timedelta`?

**Comment by elda27** [comment]
You have chosen that the type is `datetime.fromisoformat`.
It is least coverage of use cases. (equal to cover the ISO 8601 format only)
If we choose str, it covers unix time, general time format, ISO 8601format.
In this case, we prefer using str from these types because it satisfies most use cases.

We have other options to solve this problem, such as using the actions of ArgumentParser to handle input arguments, but it is sufficient.
If you propose more widely cases of datetime uses, please describe example of the input.

**Comment by yassun7010** [comment]
The problem was not adequately explained.

Pydantic interprets the `str` correctly, but the current implementation fails on the Argparse side.

The argparse type is given a `datetime` type in the current, but the expected `Callable[[str], Any]` is not satisfied, resulting in an error.

Based on the discussion in this issue, I have modified the argparse side to treat it as a `str`.

**Comment by elda27** [comment]
Yes, I know.
If you finished to modify source codes, please comment in PR page.
